### ISSUE TITLE
Can you take a look at this 1.16.5 issue?

### ISSUE THREAD

**Issue by ekiplier** [TelepathicGrunt/FeatureNBTDeadlockBeGone#1]
The way you described the issue on the CF page reminded me of what was happening in my modpack a while back. The Realistic Bees mod seemed to trigger it, so I opened the issue on the respective GitHub page, and the dev has fixed it. However, since this can also occur on 1.16.5, would you consider making a version of your Deadlock Be Gone mod for 1.16.5 so people don't run into it in their modpacks? I'm asking this because it's really hard to assess this particular type of issue. I will mention the one I opened here: 

https://github.com/ricksouth/serilum-mc-mods/issues/966

There's a crash report available there.

**Comment by TelepathicGrunt** [comment]
I’m not backporting mods as it is too much for for me to maintain multiple Mc versions. As far as I know, I don’t think the issue exists in older Mc versions. I believe it was introduced in 1.17 as that’s when Bumblezone started deadlocking when my bee dungeons intersected each other. Hence why this mod was first made for 1.17 to help my Bumblezone mod and then ported to 1.18 as Mojang hasn’t fixed it yet
